### PR TITLE
fix: use @eggjs/ajv-keywords and @eggjs/ajv-formats

### PR DESCRIPTION
**Pull request by fengmk2**
- https://github.com/eggjs/ajv-keywords/commit/1ce38b62e1181550e58926f53b2cc6963c152bde
- https://github.com/eggjs/ajv-formats/commit/8b82af10efb4421a3d9428402b0f5576c5493811

## Summary by CodeRabbit

- **Chores**
	- Updated the dependency for keyword validation in the plugin system to improve stability and compatibility.
	- Added the `ajv` package as a new dev dependency in `package.json`.

### CODE REVIEW

**Review by killagu — COMMENTED** [review]
ajv-formats 这个应该也要。

**Comment by fengmk2** [comment]
> ajv-formats 这个应该也要。

果然。。

**Comment by fengmk2** [comment]
@killagu done

**Review by killagu — APPROVED** [review]
LGTM

**Comment by fengmk2** [comment]
@killagu 发个版本

**Comment by killagu** [comment]
- @eggjs/ajv-decorator@3.36.1
 - @eggjs/aop-decorator@3.36.1
 - @eggjs/controller-decorator@3.36.1
 - @eggjs/core-decorator@3.36.1
 - @eggjs/dal-decorator@3.36.1
 - @eggjs/dal-runtime@3.36.1
 - @eggjs/egg-module-common@3.36.1
 - @eggjs/eventbus-decorator@3.36.1
 - @eggjs/standalone-decorator@3.36.1
 - @eggjs/tegg@3.36.1
 - @eggjs/tegg-ajv-plugin@3.36.1
 - @eggjs/tegg-aop-plugin@3.36.1
 - @eggjs/tegg-aop-runtime@3.36.1
 - @eggjs/tegg-background-task@3.36.1
 - @eggjs/tegg-common-util@3.36.1
 - @eggjs/tegg-config@3.36.1
 - @eggjs/tegg-controller-plugin@3.36.1
 - @eggjs/tegg-dal-plugin@3.36.1
 - @eggjs/tegg-dynamic-inject@3.36.1
 - @eggjs/tegg-dynamic-inject-runtime@3.36.1
 - @eggjs/tegg-eventbus-plugin@3.36.1
 - @eggjs/tegg-eventbus-runtime@3.36.1
 - @eggjs/tegg-lifecycle@3.36.1
 - @eggjs/tegg-loader@3.36.1
 - @eggjs/tegg-metadata@3.36.1
 - @eggjs/tegg-orm-decorator@3.36.1
 - @eggjs/tegg-orm-plugin@3.36.1
 - @eggjs/tegg-plugin@3.36.1
 - @eggjs/tegg-runtime@3.36.1
 - @eggjs/tegg-schedule-decorator@3.36.1
 - @eggjs/tegg-schedule-plugin@3.36.1
 - @eggjs/tegg-standalone@3.36.1
 - @eggjs/tegg-transaction-decorator@3.36.1

**Pull request merged**
